replicaCount: 3

image:
  repository: shubhindia/gpu-telemetry-queue
  tag: latest
  pullPolicy: Always

database:
  url: postgres://postgres:postgres@postgres-postgres:5432/gpu_telemetry?sslmode=disable

logging:
  level: info
  format: text
  addSource: false

queue:
  partitions: 4
  segmentSizeBytes: "67108864"

  replication:
    factor: 3
    requiredFollowerAcks: 1

storage:
  size: 1Gi
  storageClass: ""

service:
  port: 8080

podSelector:
  app: gpu-telemetry-queue

metrics:
  enabled: true
  path: /metrics

podAnnotations: {}

resources: {}
