apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "queue.fullname" . }}
  labels:
    {{- include "queue.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "queue.fullname" . }}
  labels:
    {{- include "queue.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "queue.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "queue.fullname" . }}