replicaCount: 1

image:
  repository: shubhindia/gpu-telemetry-streamer
  tag: latest
  pullPolicy: Always

queue:
  url: http://queue-queue:8080
  topic: gpu

csv:
  existingClaim: ""
  mountPath: /var/lib/streamer
  fileName: dcgm_metrics_20250718_134233.csv
  path: ""

config:
  queue:
    dataDir: /var/lib/queue
    partitions: 1
    segmentSizeBytes: "67108864"

    replication:
      factor: 1
      requiredFollowerAcks: 0

  streamer:
    spoolDir: /var/lib/streamer-spool
    maxSpoolBytes: "1073741824"
    retryInitial: 1s
    retryMax: 30s

  collector:
    workers: 1

  api:
    host: 0.0.0.0
    port: 8080

resources: {}
